Project.toml
src/EasyModelAnalysis.jl
test/runtests.jl

Add `get_sensitivity` to obtain GSA results

---

src/EasyModelAnalysis.jl
test/runtests.jl

Fixes #26 
```
julia> sensres = get_sensitivity(prob, 100.0, y, pbounds)
Dict{Symbol, Float64} with 5 entries:
:β_ST   => 0.877886
:β_S1   => 0.022177
:ρ_ST   => 0.93816
:ρ_β_S2 => 0.977242
:ρ_S1   => 0.0483608
```

Update output format from `get_sensitivity`

---

src/EasyModelAnalysis.jl
test/runtests.jl

Follow up for feedback on slack

Use expanded naming in gsa output

---

src/sensitivity.jl

This is necessary and was added to avoid repetition of code

Add back `_get_sensitivity`

---

src/EasyModelAnalysis.jl
test/runtests.jl

Add stop_at_threshold

---

docs/make.jl

[skip ci] fix site title

---

README.md
docs/src/tutorials/sensitivity_analysis.md
docs/src/tutorials/threshold_interventions.md
src/sensitivity.jl

Use batching for gsa

---

docs/src/examples/ASIR.md
test/examples.jl
test/runtests.jl

Add Asymptomatic SIR

---

docs/src/examples/ASIR.md
test/examples.jl

Add SEIRHD

---

docs/src/examples/ASIR.md
test/datafit.jl
test/examples.jl

https://github.com/SciML/EasyModelAnalysis.jl/issues/32 seems to work without additional effort.

test fitting observables

---

src/sensitivity.jl

Expand sensitivity docs

---

docs/src/getting_started.md

Because apparently nobody knows you can do that? haha it's our best feature. Fixes https://github.com/SciML/EasyModelAnalysis.jl/issues/32

add a note about observables

---

docs/src/api/data_fitting_calibration.md
src/EasyModelAnalysis.jl
src/datafit.jl
test/datafit.jl

Should be the end of fixes https://github.com/SciML/EasyModelAnalysis.jl/issues/31

Refactor datafit global

---

docs/src/scenarios/scenario4.md

@YingboMa I put in a stub for your implementation of #88.

Sketch Scenario 4

---

docs/src/scenarios/scenario3.md

So that others can rebase for testing

get the full build to work

---

src/EasyModelAnalysis.jl
src/intervention.jl
test/threshold.jl

```julia
using EasyModelAnalysis
@variables t x(t)
@parameters p
D = Differential(t)
eqs = [D(x) ~ p * x]
@named sys = ODESystem(eqs)
prob = ODEProblem(sys, [x => 0.01], (0.0, Inf), [p => 1.0])
opt_ps, (s1, s2, s3), ret = optimal_parameter_intervention_for_threshold(prob, x, 3,
abs(p)^2, [p],
[-5.0], [0.0],
(2.0, 45.0), 50);
plot(s1, lab = "pre-intervention")
plot!(s2, lab = "intervention")
plot!(s3, xlims = (0, s3.t[end]), ylims = (0, 5), lab = "post-intervention", dpi = 300)
```

Add optimal_parameter_intervention_for_threshold

---

src/EasyModelAnalysis.jl
src/datafit.jl
test/datafit.jl

Add model_forecast_score

---

src/EasyModelAnalysis.jl
src/basics.jl
src/sensitivity.jl
test/sensitivity.jl

Add maximum function support for sensitivity

---

src/intervention.jl
src/threshold.jl
test/threshold.jl

Add inequality constraint support for `optimal_parameter_threshold`

---

src/sensitivity.jl
test/sensitivity.jl

We don't want to recompute sensitivity just to plot it.

Add `create_sensitivity_plot(sensres, pbounds)`
